-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--################

--## AUTOSTART ###

--################

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})




-- Stores only text data


-- Stores only image data






-- set a random wallpaper at start and start hyprpaper

--exec-once = awww-daemon & sleep 1; $HOME/.config/hypr/scripts/wallpapers/set-random.sh


--exec-once = waydroid session start


-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprctl dispatch workspace 1")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("xrandr --output DP-1 --primary")
    hl.exec_cmd("nvibrant 0 512 512 0")
    hl.exec_cmd("sleep 1 && waybar")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("aww-deamon")
end)

-- Shutdown
hl.on("hyprland.shutdown", function()
    hl.exec_cmd("killall -u " .. os.getenv("USER"))
end)
