-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")

hl.env("HYPRCURSOR_SIZE", 24)

-- Garantir que o cursor seja aplicado na inicialização


--flatpak

hl.env("XDG_DATA_DIRS", os.getenv("HOME") .. "/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share")

-- NVIDIA

hl.env("LIBVA_DRIVER_NAME", "nvidia")

hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

-- Wayland

hl.env("OZONE_PLATFORM", "wayland")

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")

hl.env("NVD_BACKEND", "direct")

-- NVIDIA Shader Cache

hl.env("__GL_SHADER_DISK_CACHE", 1)

hl.env("__GL_SHADER_DISK_CACHE_SIZE", 10737418240)

hl.env("__GL_SYNC_TO_VBLANK", 0)

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 24")
end)
