-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        gaps_in = 2,
        gaps_out = 0,
        border_size = 0,
        resize_on_border = true,
        allow_tearing = true,
        layout = "dwindle",
        col = {
            active_border = "rgb(bbbbbb)",
            inactive_border = "rgb(666666)",
        },
    },
})

hl.config({
    decoration = {
        rounding = 10,
        rounding_power = 2,
        active_opacity = 1,
        inactive_opacity = 1,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgb(15161e)",
        },
        blur = {
            enabled = true,
            size = 6,
            passes = 4,
            vibrancy = 0.1696,
        },
    },
})
