-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--############

--## INPUT ###

--############

-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "us",
        kb_options = "grp:win_space_toggle",
        follow_mouse = 1,
        accel_profile = "flat",
        -- force_no_accel = true
    },
})

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})
