-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Variables

local inFocusOpacity = 1

local notInFocusOpacity = 0.7

hl.window_rule({
    name  = "suppress_event_maxim",
    match = {
        class.* = true,
    },
    -- TODO: review rule: "suppress_event maximize"
})

-- Fix some dragging issues with XWayland

hl.window_rule({
    name  = "no_focus_on",
    match = {
        class = "^$",
        title = "^$",
        xwayland = 1,
        float = 1,
        fullscreen = 0,
        pin = 0,
    },
    -- TODO: review rule: "no_focus on"
})

-- Default opacity for all windows

hl.window_rule({
    name  = "opacity__infocusopac",
    match = {
        class.* = true,
    },
    opacity = "1 0.7",
})

-- Kitty fully opaque

hl.window_rule({
    name  = "opacity_0_85_0_85",
    match = {
        class = "^kitty$",
    },
    opacity = "0.85 0.85",
})

-- Browsers

hl.window_rule({
    name  = "opacity__infocusopac",
    match = {
        class = "^(firefox|brave|chromium|librewolf|qutebrowser|zen-browser)$",
    },
    opacity = "1 0.7",
})

-- Spotify / Discord / VS Code / Thunar or Nemo by title

hl.window_rule({
    name  = "opacity__infocusopac",
    match = {
        title.*Spotify.* = true,
    },
    opacity = "1 0.7",
})

hl.window_rule({
    name  = "opacity__infocusopac",
    match = {
        title.*Discord.* = true,
    },
    opacity = "1 0.7",
})

hl.window_rule({
    name  = "opacity__infocusopac",
    match = {
        title.*Code.* = true,
    },
    opacity = "1 0.7",
})

hl.window_rule({
    name  = "opacity__infocusopac",
    match = {
        title.*(Thunar|nemo).* = true,
    },
    opacity = "1 0.7",
})

hl.window_rule({
    name  = "center_on",
    match = {
        float = 1,
    },
    center = true,
})

-- Lunar Client fullscreen (static effect)

hl.window_rule({
    name  = "fullscreen_on",
    match = {
        class = "^Lunar Client.*$",
    },
    fullscreen = true,
})
