# Workspace 1 no DP-1 (monitor principal)
workspace = 1, monitor:DP-1, default:true
workspace = 2, monitor:HDMI-A-1, default:true 
# Workspaces 2,4,5 no HDMI-A-1 (monitor secundário)
workspace = 3, monitor:DP-1, default:true
workspace = 4, monitor:HDMI-A-1, default:true
  

