-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Workspace 1 no DP-1 (monitor principal)

hl.workspace_rule({
    workspace = 1,
    monitor = "DP-1",
    is_default = true,
})

hl.workspace_rule({
    workspace = 2,
    monitor = "HDMI-A-1",
    is_default = true,
})

-- Workspaces 2,4,5 no HDMI-A-1 (monitor secundário)

hl.workspace_rule({
    workspace = 3,
    monitor = "DP-1",
    is_default = true,
})

hl.workspace_rule({
    workspace = 4,
    monitor = "HDMI-A-1",
    is_default = true,
})
