-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- source = ~/.config/hypr/configs/monitors.conf -> requires manual conversion
-- local monitors = require("configs.monitors")
-- TODO: convert ~/.config/hypr/configs/monitors.conf to .lua and use require()

-- source = ~/.config/hypr/configs/autostart.conf -> requires manual conversion
-- local autostart = require("configs.autostart")
-- TODO: convert ~/.config/hypr/configs/autostart.conf to .lua and use require()

-- source = ~/.config/hypr/configs/env.conf -> requires manual conversion
-- local env = require("configs.env")
-- TODO: convert ~/.config/hypr/configs/env.conf to .lua and use require()

-- source = ~/.config/hypr/configs/hyprcolors.conf -> requires manual conversion
-- local hyprcolors = require("configs.hyprcolors")
-- TODO: convert ~/.config/hypr/configs/hyprcolors.conf to .lua and use require()

-- source = ~/.config/hypr/configs/animations.conf -> requires manual conversion
-- local animations = require("configs.animations")
-- TODO: convert ~/.config/hypr/configs/animations.conf to .lua and use require()

-- source = ~/.config/hypr/configs/general.conf -> requires manual conversion
-- local general = require("configs.general")
-- TODO: convert ~/.config/hypr/configs/general.conf to .lua and use require()

-- source = ~/.config/hypr/configs/input.conf -> requires manual conversion
-- local input = require("configs.input")
-- TODO: convert ~/.config/hypr/configs/input.conf to .lua and use require()

-- source = ~/.config/hypr/configs/keybinds.conf -> requires manual conversion
-- local keybinds = require("configs.keybinds")
-- TODO: convert ~/.config/hypr/configs/keybinds.conf to .lua and use require()

-- source = ~/.config/hypr/configs/windowrule.conf -> requires manual conversion
-- local windowrule = require("configs.windowrule")
-- TODO: convert ~/.config/hypr/configs/windowrule.conf to .lua and use require()

-- source = ~/.config/hypr/configs/workspaces.conf -> requires manual conversion
-- local workspaces = require("configs.workspaces")
-- TODO: convert ~/.config/hypr/configs/workspaces.conf to .lua and use require()

-- source = ~/.config/hypr/configs/debug.conf -> requires manual conversion
-- local debug = require("configs.debug")
-- TODO: convert ~/.config/hypr/configs/debug.conf to .lua and use require()



-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("sleep 1 && awww restore")
end)
