-- MONITORS & WORKSPACES
-- ============================================================
-- Auto-generated by install.sh
--
-- Monitors are sorted by resolution (largest = primary at 0x0).
--
-- Position reference:
--   "0x0"    -> primary monitor (origin point, centered)
--   "Wx0"    -> monitor placed to the RIGHT of the previous one
--   "-Wx0"   -> monitor placed to the LEFT of the previous one
--
-- If your secondary monitor is physically on the LEFT side,
-- edit its position to a negative value.
-- Example: "-1920x0" places the monitor to the LEFT.
-- ============================================================
local M = {}

function M.setup()
    hl.monitor({ output = "DP-1", mode = "1920x1080@180", position = "0x0", scale = 1 })
    hl.monitor({ output = "HDMI-A-1", mode = "1366x768@60", position = "1920x0", scale = 1 })

    -- ============================================================
    -- WORKSPACES
    -- ============================================================
    hl.workspace_rule({ workspace = 1, monitor = "DP-1", persistent = true })
    hl.workspace_rule({ workspace = 2, monitor = "DP-1", persistent = true })
    hl.workspace_rule({ workspace = 3, monitor = "DP-1", persistent = true })
    hl.workspace_rule({ workspace = 4, monitor = "DP-1", persistent = true })
    hl.workspace_rule({ workspace = 6, monitor = "HDMI-A-1", persistent = true, default = true })
end

return M
